#!/usr/bin/env python

import os
import urllib.parse
import random


def qute_command(command):
    with open(os.environ["QUTE_FIFO"], "w") as fifo:
        fifo.write(command + "\n")
        fifo.flush()


title = os.getenv("QUTE_TITLE")
url = urllib.parse.urlparse(os.getenv("QUTE_URL"))
qs = urllib.parse.parse_qs(url.query)

if (
    "youtube.com" in url.netloc
    or "invidious" in title.lower()
    or "invidious" in url.netloc
    or "piped" in title.lower()
    or "piped" in url.netloc
):
    alt = random.choice(["invidious", "piped"])
    path = url.path + "?" + url.query

    if alt == "invidious":
        if url.path.startswith("/results"):
            path = f'/search?q={qs["search_query"]}'
        elif url.path.startswith("/search"):
            pass
        elif url.path.startswith("/watch"):
            pass
    elif alt == "piped":
        if url.path.startswith("/results"):
            pass
        elif url.path.startswith("/search"):
            path = f'/results?q={qs["q"]}'
        elif url.path.startswith("/watch"):
            pass

    qute_command(f"open https://farside.link/{alt}{path}")

if (
    "reddit.com" in url.netloc
    or "teddit" in title.lower()
    or "teddit" in url.netloc
    or "libreddit" in title.lower()
    or "libreddit" in url.netloc
):
    alt = random.choice(["teddit", "libreddit"])
    qute_command(f"open https://farside.link/{alt}{url.path}")

if "medium.com" in url.netloc or "scribe" in title.lower() or "scribe" in url.netloc:
    qute_command(f"open https://farside.link/scribe{url.path}")

if (
    "wikipedia.org" in url.netloc
    or "Wikipedia" in title.lower()
    or "wikiless" in url.netloc
):
    qute_command(f"open https://farside.link/wikiless{url.path}")

if (
    "instagram.com" in url.netloc
    or "bibliogram" in title.lower()
    or "bibliogram" in url.netloc
):
    if "instagram.com" in url.netloc and not url.path.startswith("/p/"):
        qute_command(f"open https://farside.link/bibliogram/u{url.path}")

    qute_command(f"open https://farside.link/bibliogram{url.path}")

if "twitter.com" in url.netloc or "nitter" in title.lower() or "nitter" in url.netloc:
    qute_command(f"open https://farside.link/nitter{url.path}")
