#!/usr/bin/env python

import os
import sys
import random


def qute_command(command):
    with open(os.environ["QUTE_FIFO"], "w") as fifo:
        fifo.write(command + "\n")
        fifo.flush()


word = sys.argv[1] if len(sys.argv) > 1 else os.getenv("QUTE_SELECTED_TEXT")
if not word:
    sys.exit(0)

alt = random.choice(["simplytranslate", "lingva"])

if alt == "lingva":
    qute_command(f"open -t https://farside.link/lingva/auto/en/{word}")
elif alt == "simplytranslate":
    qute_command(
        f"open -t https://farside.link/simplytranslate/?engine=google&text={word}&sl=auto&tl=en"
    )
